# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: ad84204e04f023d1f9c31307716361d80864a4abecf6877a556edeabd44177a4cc555cd9c7a08ea82d8ac8ae1c1736074d77067e84e944aa43a55ab455705173

test:
  secret_key_base: e00d60f0f2605eaaa1ed50ba46cabe6d36a1034099a7892edbd62ea34698f591a36dc54b335fef6e3aba13ce90ca6a6c14f3041a60d2cfaec17f8fc5388238f8

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
